# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  # Local only podspec will download source zip
  # 开发使用path
#  pod 'AMap3DMap-NO-IDFA-XC', :path => '../'

#测试使用 podspec
  pod 'AMap3DMap-NO-IDFA-XC', :podspec => '../'

#pod 'AMapFoundation-NO-IDFA-XC', '~> 1.0.7'


end
